### ISSUE TITLE
Merge AlephBFT into Blockchain sample node

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#322]
For our hackathon we started: https://github.com/prince-chrismc/pyrsia-sandbox/tree/aleph-substrate-node

This needs to be rebased and moved to the example + library so we can get starting with making improvements

- [x] Seperate network code #332 
- [x] Align signature struct #333 
- [x] Hasher Trait #421 
- [x] Authority Pen #432
- [x] Authority Verifier and Key Verifier #439
- [x] KeyBox implementation #464 
- [x] Add codec support #535
- [ ] Network and Chain Session #600 

***

KeyBox requires index < count so the index can not be the peer id. each node will have it's own mapping 😱

**Comment by prince-chrismc** [comment]
## Criteria

- have all the code compile in this repository
- example should do consensus over AlephBFT

**Comment by prince-chrismc** [comment]
This is blocked by https://github.com/pyrsia/pyrsia/issues/320
