### ISSUE TITLE
Create a second iteration Artifact manager to use Kademlia to find an artifact with a given hash and retrieve it.

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#57]
This task is to enhance the artifact manager to use Kademlia to find a node that has an artifact with a particular hash. Once it has found a node that has the artifact, it should communicate with that node's artifact manager to copy the artifact. This iteration will copy the entire artifact from one other node. 

Parallel copying is out of scope in this version.

- [x] Add Kademlia behavior #47 #85
   - [ ] Rename `MyBehavoir` to something better
- [x] docker api to swarm connection #85 
- [] return message (swarm to docker) handled #111 
- [ ] search others nodes (query network)
   - [ ] advertise records?
   - [ ] answer other nodes
- [ ] check locally (read disk for blobs)
- [ ] network transfer of blobs

**Comment by prince-chrismc** [comment]
Just testing workflow automations

**Comment by erwin1** [comment]
this can be closed and is followed up by #363 and #468 and probably some other issues labeled p2p
